apiVersion: apps/v1
kind: Deployment
metadata:
  name: look
spec:
  replicas: 1
  selector:
    matchLabels:
      app: look
  template:
    metadata:
      labels:
        app: look
    spec:
      containers:
      - image: okteto.dev/look:latest
        name: look
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2ed35931-a718-4d4d-afda-b54fec26e70d"
        - name: Vless_Path
          value: "/grtywrd0"
        - name: Vmess_UUID
          value: "2ed35931-a718-4d4d-afda-b54fec26e70d"
        - name: Vmess_Path
          value: "/md45bjui7hg65"
        - name: Share_Path
          value: "/v2link"
